name: Publish

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
# https://github.com/taiki-e/upload-rust-binary-action
jobs:
  publish_specific_test1:
    name: publish(test1) - ${{ matrix.os }} - ${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        features: ["auth"]

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: test1
          tar: unix
          zip: windows
          archive: $bin-$target-${{ matrix.features }}
          token: ${{ secrets.GITHUB_TOKEN }}
          features: ${{ matrix.features }}

  publish_default_test1:
    name: publish(test1) - ${{ matrix.os }} - default
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: test1
          archive: app-$target
          token: ${{ secrets.GITHUB_TOKEN }}

  publish_default_test2:
    name: publish(test2) - ${{ matrix.os }} - default
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: test2
          archive: app-$target
          token: ${{ secrets.GITHUB_TOKEN }}